# Schema for the configuration files of the Drupalfr social module.

drupalfr_social.twitter:
  type: config_object
  label: 'Settings for Twitter connection'
  mapping:
    consumer_key:
      type: string
      label: 'Consumer key'
    consumer_secret:
      type: string
      label: 'Consumer secret'
    access_token:
      type: string
      label: 'Access token'
    access_token_secret:
      type: string
      label: 'Access token secret'

block.settings.follow_us_block:
  type: block_settings
  label: 'Follow us block settings.'
  mapping:
    url_facebook:
      type: string
      label: 'Facebook URL'
    url_twitter:
      type: string
      label: 'Twitter URL'
    url_linkedin:
      type: string
      label: 'LinkedIn URL'
    url_viadeo:
      type: string
      label: 'Viadeo URL'
    url_youtube:
      type: string
      label: 'Youtube URL'
