version: "2"

services:
  web:
    image: httpd:2.4-alpine
    volumes:
      - ./conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/httpd/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - .:/project
    depends_on:
      - php
      - mysql
      - redis
      - mail
      - solr
    networks:
      default:
        ipv4_address: 172.18.0.2


  php:
    image: florenttorregrosa/drupal-php-dev:7.0-fpm-alpine
    volumes:
      - .:/project
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
    networks:
      default:
        ipv4_address: 172.18.0.3


  varnish:
    image: florenttorregrosa/docker-varnish:latest
    depends_on:
      - web
    environment:
      VCL_CONFIG: /varnish-drupal/varnish.vcl
    volumes:
      - ./conf/varnish:/varnish-drupal
    networks:
      default:
        ipv4_address: 172.18.0.4


  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    networks:
      default:
        ipv4_address: 172.18.0.5


  solr:
    image: solr:6.1.0-alpine
    volumes:
      - ./conf/solr:/solr-drupal/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /solr-drupal
    networks:
      default:
        ipv4_address: 172.18.0.6


  redis:
    image: redis:3.2.1-alpine
    networks:
      default:
        ipv4_address: 172.18.0.7


  mail:
    image: djfarrelly/maildev
    networks:
      default:
        ipv4_address: 172.18.0.8


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.1
