version: "2"

services:
  web:
    image: florenttorregrosa/docker-drupal-dev:php7
    depends_on:
      - mysql
      - redis
      - mail
      - solr
    volumes:
      - .:/project
    networks:
      default:
        ipv4_address: 172.18.0.2


  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.3


  solr:
    image: solr:6.1.0-alpine
    volumes:
      - ./conf/solr:/solr-drupal/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /solr-drupal
    networks:
      default:
        ipv4_address: 172.18.0.4


  redis:
    image: redis:3.2.1-alpine
    networks:
      default:
        ipv4_address: 172.18.0.5


  mail:
    image: djfarrelly/maildev
    networks:
      default:
        ipv4_address: 172.18.0.6


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.1
