_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
langcode: fr
minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
max_shown_results: null
use_relative_width: false
jquery_selector: '.views-exposed-form select'
search_contains: false
disable_search: false
allow_single_deselect: false
disabled_themes:
  seven: '0'
  zurb_foundation: '0'
  drupal_france: '0'
chosen_include: 1
placeholder_text_multiple: 'Selectionner une ou plusieurs options  '
placeholder_text_single: 'Selectionner une option'
no_results_text: 'Aucun r√©sultat'
