domain: ''
domains_option: 1
domains_list: ''
eu_only: null
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
export:
  folder: custom
langcode: fr
popup_agreed:
  value: "<h2>Merci d'avoir accepté les cookies</h2>\r\n\r\n<p>Vous pouvez désormais masquer ce message ou en apprendre plus à propos des cookies.</p>\r\n"
  format: full_html
popup_agree_button_message: 'Oui, je suis d''accord'
popup_agreed_enabled: false
popup_bg_hex: ''
popup_clicking_confirmation: true
popup_delay: 1000
popup_disagree_button_message: 'Non, je désire de plus amples informations'
popup_enabled: true
popup_find_more_button_message: 'Plus d''infos'
popup_height: null
popup_hide_agreed: true
popup_hide_button_message: Masquer
popup_info:
  value: "<h2>Nous utilisons des cookies sur ce site pour améliorer votre expérience d'utilisateur.</h2>\r\n\r\n<p>En cliquant sur un lien de cette page, vous nous donnez votre consentement de définir des cookies.</p>\r\n"
  format: full_html
popup_link: /mentions-legales
popup_link_new_window: true
popup_position: false
popup_text_hex: ''
popup_width: ''
_core:
  default_config_hash: 8DEBPceUEPO-Cf2mpfehjO317-zCaAjJUE9dru6EC-8
cookie_lifetime: 100
mobile_popup_info:
  value: ''
  format: full_html
show_disagree_button: true
popup_scrolling_confirmation: false
use_mobile_message: false
mobile_breakpoint: 768
exclude_admin_theme: true
eu_only_js: null
use_bare_css: false
disagree_do_not_show_popup: false
reload_page: false
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
fixed_top_position: false
script_scope: footer
