domain: ''
domains_option: 1
domains_list: ''
eu_only: false
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
export:
  folder: custom
langcode: fr
popup_agreed:
  value: "<h2>Merci d'avoir accepté les cookies</h2>\r\n\r\n<p>Vous pouvez désormais masquer ce message ou en apprendre plus à propos des cookies.</p>\r\n"
  format: full_html
popup_agree_button_message: OK
popup_agreed_enabled: false
popup_bg_hex: 01273A
popup_clicking_confirmation: true
popup_delay: 1
popup_disagree_button_message: 'Non, donnez moi plus d''informations'
popup_enabled: true
popup_find_more_button_message: 'Plus d''infos'
popup_height: null
popup_hide_agreed: true
popup_hide_button_message: Masquer
popup_info:
  value: "<h2>Nous utilisons des cookies sur ce site pour améliorer votre expérience utilisateur</h2>\r\n\r\n<p>En cliquant sur n'importe quel lien de cette page vous nous donnez votre consentement pour envoyer des cookies.</p>\r\n"
  format: full_html
popup_link: 'internal:/home'
popup_link_new_window: true
popup_position: false
popup_text_hex: ffffff
popup_width: 100%
_core:
  default_config_hash: 8DEBPceUEPO-Cf2mpfehjO317-zCaAjJUE9dru6EC-8
