attribute_enable:
  title: true
  id: true
  name: true
  rel: true
  class: true
  style: false
  target: true
  accesskey: true
attribute_default:
  title: ''
  id: ''
  name: ''
  rel: ''
  class: ''
  style: ''
  target: ''
  accesskey: ''
_core:
  default_config_hash: MhLLiI0DpuBm9-5eSUO6nTwGAh2OFiFQ1XwQTJCznkg
langcode: fr
