canonical: true
auto_redirect: true
default_status_code: 301
passthrough_querystring: true
warning: false
ignore_admin_path: false
access_check: false
content_location_header: false
route_normalizer_enabled: true
_core:
  default_config_hash: sy2s6cD5e-MOs_pCF0bLhRG9-YLooOXHSWn-00asCCc
langcode: fr
